
networks:
  internal_network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - internal_network
    volumes:
      - media_volume:/app/media
      - static_volume:/app/static
    env_file:
      - .env
    depends_on:
      - db
      - redis

  redis:
    image: redis:7-alpine
    networks:
      - internal_network

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"  # Expose only Nginx to the host
    networks:
      - internal_network
    volumes:
      - static_volume:/static
      - media_volume:/app/media

      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  
  db:
      image: postgres:15-alpine
      restart: always
      networks:
        - internal_network

      volumes:
        - pg_volume:/var/lib/postgresql/data # Mounted for persistent storage
      environment:
        - "POSTGRES_USER: ${POSTGRES_USER}"
        - "POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}"
        - "POSTGRES_DB: ${POSTGRES_DB}"
      ports:
        - "5432:5432"

  db-adminer:
    image: adminer
    restart: always
    ports:
      - "5433:8080"

volumes:
  static_volume:
  media_volume:
  pg_volume: